language: scala

script:
  - sbt ++2.11.12 readme/run
  - sbt ++$TRAVIS_SCALA_VERSION scalatagsJVM/test scalatagsJS/test

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1

jdk:
  - oraclejdk8
  - openjdk11

env:
  - SCALAJS_VERSION="0.6.26"
  - SCALAJS_VERSION="1.0.0-M6

sudo: false

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.coursier
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
